version: '3.8'
services:
  db-postgres:
    container_name: postgres-hacktiv
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_rest_api
    ports:
      - "5432:5432"

  db-mysql:
    container_name: mysql-hacktiv
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hacktiv
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"